// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
import { config as loadEnv } from 'dotenv';
import { defineConfig } from "prisma/config";

loadEnv();

const datasourceUrl =
  process.env.DATABASE_URL ??
  process.env.TURSO_DATABASE_URL ??
  "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: datasourceUrl,
  },
});
